version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.2
    - 3.25.3
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.1
    - 3.25.3
  - dependency-name: ember-template-lint
    versions:
    - 3.1.1
  - dependency-name: node-html-light
    versions:
    - 2.0.0
    - 2.2.0
  commit-message:
    prefix: ""
  registries:
  - npm-registry-npm-pkg-github-com
